image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_CONTAINER_IMAGE
  CONTAINER_RELEASE_IMAGE: $CI_CONTAINER_IMAGE

stages:
  - install
  - build
  - release

before_script:
  - apk add --no-cache nodejs yarn
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn build
  dependencies:
    - install

release-image:
  stage: release
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
