image: docker:latest

services:
  - docker:dind

variables:
  version: 0.1.0
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_RELEASE_IMAGE_VERSION: $CI_CONTAINER_IMAGE:v$version
  CONTAINER_RELEASE_IMAGE_LATEST: $CI_CONTAINER_IMAGE:latest

stages:
  - install
  - build
  - test
  - release

before_script:
  - apk add --no-cache nodejs yarn
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn build
  dependencies:
    - install

lint:
  stage: test
  script:
    - yarn lint
  dependencies:
    - install

test:
  stage: test
  script:
    - yarn test:ci
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/reports/junit.xml
  coverage: '/All files.*?\s+(\d+.\d+)/'
  dependencies:
    - install

deploy:
  stage: release
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE_VERSION .
    - docker tag $CONTAINER_RELEASE_IMAGE_VERSION $CONTAINER_RELEASE_IMAGE_VERSION
    - docker push $CONTAINER_RELEASE_IMAGE_VERSION
    - docker tag $CONTAINER_RELEASE_IMAGE_VERSION $CONTAINER_RELEASE_IMAGE_LATEST
    - docker push $CONTAINER_RELEASE_IMAGE_LATEST
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never
